version: "3.8"

services:

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: studentdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend

  springboot:
    build:
      context: ./backend
      dockerfile: Dockerfile
      container_name: springboot
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/studentdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
    ports:
      - "8080:8010"
    networks:
      - backend

  angular:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: angular
    ports:
      - "4200:80"
    depends_on:
      - springboot
    networks:
      - backend

volumes:
  mysql-data:

networks:
  backend:
